# Generated by Django 6.0 on 2025-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_ngo',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register_ngo',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
