# Generated by Django 6.0 on 2025-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0002_alter_register_ngo_mobile_alter_register_ngo_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='register_ngo',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
