# Generated by Django 5.2.9 on 2025-12-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0003_delete_login_register_ngo_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_type', models.CharField(choices=[('student', 'Student Volunteer'), ('organization', 'Organization Volunteer'), ('individual', 'Individual Volunteer')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=50, null=True)),
                ('government_id', models.CharField(blank=True, max_length=50, null=True)),
                ('social_credits', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='register_ngo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('pickup', 'Food Pickup'), ('delivery', 'Food Delivery'), ('donation_request', 'Donation Request')], max_length=20)),
                ('pickup_location', models.TextField()),
                ('delivery_location', models.TextField(blank=True, null=True)),
                ('food_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('credit_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nour.volunteer')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_tasks', to='nour.register_ngo')),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_tasks', to='nour.register_ngo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_earned', models.IntegerField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Task completion reward', max_length=200)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='nour.volunteer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nour.volunteertask')),
            ],
        ),
    ]
