# Generated by Django 6.0 on 2025-12-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nour', '0004_volunteer_alter_register_ngo_id_volunteertask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO')], max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('addr', models.TextField()),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='socialcredit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteertask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteertask',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_tasks', to='nour.register_users'),
        ),
        migrations.AlterField(
            model_name='volunteertask',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_tasks', to='nour.register_users'),
        ),
        migrations.DeleteModel(
            name='register_ngo',
        ),
    ]
